# Generated by Django 6.0 on 2026-01-05 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类型名')),
            ],
            options={
                'verbose_name': '品类',
                'verbose_name_plural': '品类',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='角色名')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='characters/', verbose_name='角色头像')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='作品名')),
                ('short_name', models.CharField(help_text='例如：星铁、HSR', max_length=50, verbose_name='简称 / 搜索关键字')),
            ],
            options={
                'verbose_name': 'IP作品',
                'verbose_name_plural': 'IP作品',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='资产ID')),
                ('name', models.CharField(max_length=200, verbose_name='谷子名称')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='goods/main/', verbose_name='主图')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='购入单价')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='入手时间')),
                ('is_official', models.BooleanField(default=True, verbose_name='是否官谷')),
                ('status', models.CharField(choices=[('in_cabinet', '在馆'), ('outdoor', '出街中'), ('sold', '已售出')], default='in_cabinet', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='goods.category', verbose_name='品类')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='goods.character', verbose_name='角色')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='location.storagenode', verbose_name='物理位置')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='goods.ip', verbose_name='IP作品')),
            ],
            options={
                'verbose_name': '谷子',
                'verbose_name_plural': '谷子',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuziImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goods/extra/', verbose_name='补充图片')),
                ('label', models.CharField(blank=True, help_text='如：背板细节、瑕疵点', max_length=100, null=True, verbose_name='图片标签')),
                ('guzi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_photos', to='goods.goods', verbose_name='关联谷子')),
            ],
            options={
                'verbose_name': '谷子补充图片',
                'verbose_name_plural': '谷子补充图片',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='goods.ip', verbose_name='所属作品'),
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('ip', 'name')},
        ),
    ]
