# Generated by Django 6.0 on 2026-01-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='角色名'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='谷子名称'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='作品名'),
        ),
    ]
