# Generated by Django 5.2.9 on 2026-01-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_character_gender_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_at'], 'verbose_name': '品类', 'verbose_name_plural': '品类'},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['created_at'], 'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.AlterModelOptions(
            name='ip',
            options={'ordering': ['created_at'], 'verbose_name': 'IP作品', 'verbose_name_plural': 'IP作品'},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='character',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='ip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他')], default='female', max_length=10, verbose_name='角色性别'),
        ),
    ]
