# Generated by Django 5.2.9 on 2026-01-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_alter_character_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='subject_type',
            field=models.IntegerField(blank=True, choices=[(1, '书籍'), (2, '动画'), (3, '音乐'), (4, '游戏'), (6, '三次元/特摄')], help_text='1=书籍, 2=动画, 3=音乐, 4=游戏, 6=三次元/特摄', null=True, verbose_name='作品类型'),
        ),
    ]
