# Generated by Django 5.2.9 on 2026-01-09 05:30

from django.db import migrations, models


def convert_avatar_to_string(apps, schema_editor):
    """将ImageField的avatar转换为字符串路径"""
    Character = apps.get_model('goods', 'Character')
    
    for character in Character.objects.all():
        try:
            # 在字段类型改变前，avatar仍然是ImageField
            # 保存现有文件路径到临时字段avatar_temp
            if character.avatar:
                avatar_path = character.avatar.name
                # 保存到临时字段
                Character.objects.filter(pk=character.pk).update(avatar_temp=avatar_path)
        except Exception:
            # 如果转换失败，保留为空
            pass


def copy_temp_to_avatar(apps, schema_editor):
    """将临时字段数据复制回avatar字段"""
    Character = apps.get_model('goods', 'Character')
    
    for character in Character.objects.exclude(avatar_temp__isnull=True).exclude(avatar_temp=''):
        character.avatar = character.avatar_temp
        character.save(update_fields=['avatar'])


def reverse_convert_avatar(apps, schema_editor):
    """反向迁移：将字符串路径转换回ImageField（实际上不需要反向操作）"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_ip_subject_type'),
    ]

    operations = [
        # 第一步：添加临时字段用于保存数据
        migrations.AddField(
            model_name='character',
            name='avatar_temp',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        # 第二步：数据迁移：将ImageField数据转换为字符串保存到临时字段
        migrations.RunPython(convert_avatar_to_string, reverse_convert_avatar),
        # 第三步：删除原ImageField字段
        migrations.RemoveField(
            model_name='character',
            name='avatar',
        ),
        # 第四步：添加新的CharField字段avatar
        migrations.AddField(
            model_name='character',
            name='avatar',
            field=models.CharField(blank=True, help_text='角色头像路径或URL。可以是服务器内的相对路径（如 characters/xxx.jpg）或外部URL（如 https://example.com/avatar.jpg）', max_length=500, null=True, verbose_name='角色头像'),
        ),
        # 第五步：将临时字段数据复制回avatar字段
        migrations.RunPython(copy_temp_to_avatar, reverse_convert_avatar),
        # 第六步：删除临时字段
        migrations.RemoveField(
            model_name='character',
            name='avatar_temp',
        ),
    ]
