# Generated by Django 5.2.8 on 2026-01-19 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_change_character_avatar_to_charfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'id'], 'verbose_name': '品类', 'verbose_name_plural': '品类'},
        ),
        migrations.AddField(
            model_name='category',
            name='color_tag',
            field=models.CharField(blank=True, help_text='用于UI展示的颜色标识，例如：#FF5733', max_length=20, null=True, verbose_name='颜色标签'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, help_text='控制同级节点的展示顺序，值越小越靠前', verbose_name='排序值'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='goods.category', verbose_name='父级品类'),
        ),
        migrations.AddField(
            model_name='category',
            name='path_name',
            field=models.CharField(blank=True, db_index=True, help_text='冗余字段，例如：周边/吧唧/圆形吧唧', max_length=200, null=True, verbose_name='完整路径'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='类型名'),
        ),
    ]
