# Generated by Django 5.2.8 on 2026-01-19 06:42

from django.db import migrations


def populate_path_name(apps, schema_editor):
    """
    为现有的Category数据填充path_name字段
    如果path_name为空，则根据父节点生成，如果没有父节点则使用name
    """
    Category = apps.get_model('goods', 'Category')
    
    def build_path_name(category):
        """递归构建path_name"""
        if category.path_name:
            return category.path_name
        
        if category.parent_id:
            parent = Category.objects.get(pk=category.parent_id)
            parent_path = build_path_name(parent)
            return f"{parent_path}/{category.name}"
        else:
            return category.name
    
    # 先处理所有根节点（没有父节点的）
    root_categories = Category.objects.filter(parent__isnull=True)
    for category in root_categories:
        if not category.path_name:
            category.path_name = category.name
            category.save(update_fields=['path_name'])
    
    # 然后处理所有有父节点的节点（按层级顺序）
    # 使用广度优先的方式处理，确保父节点的path_name先被填充
    processed = set()
    while True:
        categories_to_process = Category.objects.filter(
            parent__isnull=False
        ).exclude(id__in=processed)
        
        if not categories_to_process.exists():
            break
        
        for category in categories_to_process:
            if category.parent_id in processed or Category.objects.get(pk=category.parent_id).path_name:
                if not category.path_name:
                    category.path_name = build_path_name(category)
                    category.save(update_fields=['path_name'])
                processed.add(category.id)


def reverse_populate_path_name(apps, schema_editor):
    """反向操作：清空path_name字段"""
    Category = apps.get_model('goods', 'Category')
    Category.objects.all().update(path_name=None)


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_alter_category_options_category_color_tag_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_path_name, reverse_populate_path_name),
    ]
