# Generated by Django 5.2.8 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0017_alter_theme_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="ip",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="控制IP作品的展示顺序，值越小越靠前",
                verbose_name="排序值",
            ),
        ),
        migrations.AlterModelOptions(
            name="ip",
            options={"ordering": ["order", "id"], "verbose_name": "IP作品", "verbose_name_plural": "IP作品"},
        ),
    ]

