# Generated by Django 5.2.8

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0018_ip_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThemeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="themes/extra/",
                        verbose_name="主题附加图片",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="如：海报、物料细节",
                        max_length=100,
                        null=True,
                        verbose_name="图片标签",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        blank=True,
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="goods.theme",
                        verbose_name="所属主题",
                    ),
                ),
            ],
            options={
                "verbose_name": "主题附加图片",
                "verbose_name_plural": "主题附加图片",
                "ordering": ["created_at"],
            },
        ),
    ]
