# Generated by Django 5.2.8 on 2026-02-04 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0019_themeimage'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='users.user', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showcases', to='users.user', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='theme',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='users.user', verbose_name='所属用户'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='主题名称'),
        ),
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together={('user', 'name')},
        ),
    ]
