# Generated by GPT-5.2 (manual) on 2026-02-04

from django.db import migrations, models
import django.db.models.deletion


def ensure_admin_user(apps):
    Role = apps.get_model("users", "Role")
    User = apps.get_model("users", "User")

    admin_role, _ = Role.objects.get_or_create(name="Admin")
    Role.objects.get_or_create(name="User")

    # 迁移默认回填 user_id=1，必须确保该用户存在
    if not User.objects.filter(id=1).exists():
        # 这里不设置可用密码（迁移阶段不依赖登录）；后续可用 seed_users 覆盖密码
        User.objects.create(
            id=1,
            username="admin",
            password="",
            role=admin_role,
            is_active=True,
        )


def backfill_owner(apps, schema_editor):
    ensure_admin_user(apps)

    Goods = apps.get_model("goods", "Goods")
    Theme = apps.get_model("goods", "Theme")
    Showcase = apps.get_model("goods", "Showcase")

    # 历史数据默认归属到管理员账号（ID=1）
    Goods.objects.filter(user__isnull=True).update(user_id=1)
    Theme.objects.filter(user__isnull=True).update(user_id=1)
    Showcase.objects.filter(user__isnull=True).update(user_id=1)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0020_goods_user_showcase_user_theme_user_alter_theme_name_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_owner, reverse_code=noop_reverse),
        migrations.AlterField(
            model_name="goods",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods",
                to="users.user",
                verbose_name="所属用户",
            ),
        ),
        migrations.AlterField(
            model_name="showcase",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="showcases",
                to="users.user",
                verbose_name="所属用户",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="themes",
                to="users.user",
                verbose_name="所属用户",
            ),
        ),
    ]

