# Generated by Django 6.0 on 2026-01-05 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='节点名称')),
                ('path_name', models.CharField(help_text='冗余字段，例如：书房/书架A/第3层', max_length=200, verbose_name='完整路径')),
                ('image', models.ImageField(blank=True, null=True, upload_to='location/', verbose_name='位置照片')),
                ('description', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('order', models.IntegerField(default=0, help_text='控制同级节点的展示顺序，值越小越靠前', verbose_name='排序值')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='location.storagenode', verbose_name='父级节点')),
            ],
            options={
                'verbose_name': '收纳节点',
                'verbose_name_plural': '收纳节点',
                'ordering': ['order', 'id'],
            },
        ),
    ]
