# Generated by Django 6.0 on 2026-01-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagenode',
            name='path_name',
            field=models.CharField(db_index=True, help_text='冗余字段，例如：书房/书架A/第3层', max_length=200, verbose_name='完整路径'),
        ),
    ]
