# Generated by Django 5.2.8 on 2026-02-04 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_storagenode_id'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagenode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_nodes', to='users.user', verbose_name='所属用户'),
        ),
    ]
