# Generated by GPT-5.2 (manual) on 2026-02-04

from django.db import migrations, models
import django.db.models.deletion


def backfill_owner(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    User = apps.get_model("users", "User")
    admin_role, _ = Role.objects.get_or_create(name="Admin")
    Role.objects.get_or_create(name="User")
    if not User.objects.filter(id=1).exists():
        User.objects.create(
            id=1,
            username="admin",
            password="",
            role=admin_role,
            is_active=True,
        )

    StorageNode = apps.get_model("location", "StorageNode")
    StorageNode.objects.filter(user__isnull=True).update(user_id=1)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0004_storagenode_user"),
    ]

    operations = [
        migrations.RunPython(backfill_owner, reverse_code=noop_reverse),
        migrations.AlterField(
            model_name="storagenode",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storage_nodes",
                to="users.user",
                verbose_name="所属用户",
            ),
        ),
    ]

